[versions]
agp = "8.13.1"
kotlin = "2.2.21"
ksp = "1.9.24-1.0.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
# COMPOSE
activityCompose = "1.12.1"
composeBom = "2025.12.00"
composeUI = "1.6.0"
material3 = "1.2.0"
navigationCompose = "2.8.3"
coil = "2.6.0"

# RETROFIT / GSON
retrofit = "2.9.0"
converter-gson = "2.9.0"

# ROOM
room = "2.6.1"

# COROUTINES
coroutines = "1..9.0"

# GOOGLE SIGN IN
play-services-auth = "21.2.0"

#PLUGINS
android-gradle-plugin = "8.5.2"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
#COMPOSE
androidx-navigation-compose = {group = "androidx.navigation", name = "navigation-compose", version.ref="navigationCompose"}
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#COIL
coil-compose = {module = "io.coil-kt:coil-compose", version.ref = "coil"}
#RETROFIT
retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
converter-gson = {module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson"}
#ROOM
room-runtime = {module = "androidx.room:room-runtime", version.ref = "room"}
room-compiler = {module = "androidx.room:room-compiler", version.ref = "room"}
room-ktx = {module = "androidx.room:room-ktx", version.ref = "room"}
#COROUTINES
kotlinx-coroutines-android = {module = "org.jetbrains.kotlin:kotlin-coroutines-android", version.ref = "coroutines"}
#GOOGLE SIGNIN
play-services-auth = {module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth"}

######### BUNDLES ########
[bundles]
    compose-core = [
        "androidx-compose-ui",
        "androidx-compose-material3",
        "androidx-activity-compose",
        "androidx-navigation-compose",
        "coil-compose"
    ]
    retrofit-core = [
        "retrofit",
        "converter-gson"
    ]
    room-core = [
        "room-runtime",
        "room-ktx"
    ]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }



