[versions]
agp = "8.13.2"
kotlin = "2.3.0"
java = "11"

#compose
activityCompose = "1.12.2"
composeBom = "2025.12.01"
lifecycleCompose = "2.10.0"
coroutines = "1.10.2"

#firebase
firebase-bom = "34.7.0"

#maplibre
maplibre = "12.3.1"

#androidx
coreKtx = "1.17.0"
material3 = "1.7.0"
appcompat = "1.7.1"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"


[libraries]

# Kotlin/Coroutines
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# AndroidX base
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

# Compose (BOM)
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }                  # versi√≥n gobierna por BOM
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-animation = { module = "androidx.compose.animation:animation" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Lifecycle Compose (collectAsStateWithLifecycle)
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleCompose" }

# Firebase (BOM y productos)
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }  # controla BOM
firebase-storage = { module = "com.google.firebase:firebase-storage" }      # controla BOM

# MapLibre (OSM)
maplibre-android-sdk = { module = "org.maplibre.gl:android-sdk", version.ref = "maplibre" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

[bundles]
compose-core = [
"compose-ui",
"compose-ui-graphics",
"compose-material3",
"compose-foundation",
"compose-runtime",
"compose-animation",
"activity-compose",
"lifecycle-runtime-compose"
]
firebase-core = [
    "firebase-firestore",
    "firebase-storage"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = {id = "com.google.gms.google-services", version = "4.4.4"}

